### ISSUE TITLE
Bad Gateway 502 Error 

### ISSUE THREAD

**Issue by syvee** [bcbee/Universal-Presenter-Remote-iOS#14]
This has been a great program, but since Sunday I have been getting "There was an error connecting to UPR - (Request failed with status code 502)" when I try to pair my phone to the remote software. I've had no hardware changes, but I can't guarantee there haven't been Apple updates applied. Running the remote on an iPhone 15 with iOS 17.0.3, and a Mac mini with Sonoma 14.0. I've tried from multiple phones and on two different computers (both Mac minis - one is an M1 and one is a M2)

I was dead in the water for my presentation, and I was hoping it would resolve as on Sunday I was getting Cloudflare errors when trying to go to https://universalpresenterremote.com, so I thought maybe there was a server problem. I don't get the cloudflare notification anymore, but I still can't connect the two devices. 
<img width="278" alt="Screenshot 2023-11-09 at 3 27 14 PM" src="https://github.com/bcbee/Universal-Presenter-Remote-iOS/assets/110486893/e45b430c-c9c8-4559-865d-5d4986996bff">

Any advice? I'd really like this back. It's been a God-send.

**Comment by bcbee** [comment]
Hey @syvee,

I've resolved the issue, can you please try again and let me know if you're still having issues?

This was a very strange issue caused by an expired certificate in our push notification service. This certificate was causing a bunch of issues including crashing the UPR server application, which is why you saw the 502 error. All apps in our Kubernetes cluster use short lived [origin CA certificates](https://developers.cloudflare.com/ssl/origin-configuration/origin-ca/) issued by Cloudflare. However, last week Cloudflare has a [massive outage](https://blog.cloudflare.com/post-mortem-on-cloudflare-control-plane-and-analytics-outage/) which disrupted the control plane API, including breaking certificate issuance for over a day. This normally wouldn't have been a problem, but [cert-manager](https://cert-manager.io/) has really aggressive and infinitely scaling exponential back-off. Because Cloudflare was down for so long, cert-manager stopped trying to refresh certificates and actually let them expire, assuming that the issuer would still be down if it checked (oops).

After manually forcing a rotation of the expired Origin CAs, everything came back to life. I have monitoring on the UPR app itself, but not on our downstream push notification service (to prevent sending spam push notifications we don't synthetically test the join presentation route).

Anyways, thanks for bringing this to my attention and sorry for the inconvenience!

Thanks,
Brendan

**Comment by syvee** [comment]
Wow - awesomely fast response. I can't thank you enough! Everything works perfectly again!!  Thank you, thank you!
